package com.bsoft.client.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-10-25T10:56:06.239+08:00
 * Generated source version: 3.0.15
 * 
 */
@WebServiceClient(name = "cmcc_mas_wbs", 
                  wsdlLocation = "http://172.20.16.156:5813/services/cmcc_mas_wbs?wsdl",
                  targetNamespace = "http://www.csapi.org/service") 
public class CmccMasWbs_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.csapi.org/service", "cmcc_mas_wbs");
    public final static QName CmccMasWbs = new QName("http://www.csapi.org/service", "cmcc_mas_wbs");
    static {
        URL url = null;
        try {
            url = new URL("http://172.20.16.156:5813/services/cmcc_mas_wbs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CmccMasWbs_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.20.16.156:5813/services/cmcc_mas_wbs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CmccMasWbs_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CmccMasWbs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmccMasWbs_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CmccMasWbs_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CmccMasWbs_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CmccMasWbs_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CmccMasWbs
     */
    @WebEndpoint(name = "cmcc_mas_wbs")
    public CmccMasWbs getCmccMasWbs() {
        return super.getPort(CmccMasWbs, CmccMasWbs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmccMasWbs
     */
    @WebEndpoint(name = "cmcc_mas_wbs")
    public CmccMasWbs getCmccMasWbs(WebServiceFeature... features) {
        return super.getPort(CmccMasWbs, CmccMasWbs.class, features);
    }

}
