package com.bsoft.client.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-10-25T10:56:06.197+08:00
 * Generated source version: 3.0.15
 * 
 */
@WebService(targetNamespace = "http://www.csapi.org/service", name = "cmcc_mas_wbs")
@XmlSeeAlso({com.bsoft.client.schema.ap.ObjectFactory.class, com.bsoft.client.schema.common.v2_0.ObjectFactory.class, com.bsoft.client.schema.mms.ObjectFactory.class, com.bsoft.client.schema.location.ObjectFactory.class, com.bsoft.client.schema.wap.ObjectFactory.class, com.bsoft.client.schema.ussd.ObjectFactory.class, com.bsoft.client.schema.sms.ObjectFactory.class, com.bsoft.client.schema.notification.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CmccMasWbs {

    @WebMethod(action = "http://www.csapi.org/service/getPushDeliveryStatus")
    @WebResult(name = "getPushDeliveryStatusResponse", targetNamespace = "http://www.csapi.org/schema/wap", partName = "getPushDeliveryStatusResponse")
    public com.bsoft.client.schema.wap.GetPushDeliveryStatusResponse getPushDeliveryStatus(
        @WebParam(partName = "getPushDeliveryStatusRequest", name = "getPushDeliveryStatusRequest", targetNamespace = "http://www.csapi.org/schema/wap")
        com.bsoft.client.schema.wap.GetPushDeliveryStatusRequest getPushDeliveryStatusRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "APStatusRep", action = "http://www.csapi.org/service/APStatusRep")
    @WebResult(name = "APStatusRepRsp", targetNamespace = "http://www.csapi.org/schema/ap", partName = "APStatusRepRsp")
    public com.bsoft.client.schema.ap.APStatusRepRsp apStatusRep(
        @WebParam(partName = "APStatusRepReq", name = "APStatusRepReq", targetNamespace = "http://www.csapi.org/schema/ap")
        com.bsoft.client.schema.ap.APStatusRepReq apStatusRepReq
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/getLocationForGroup")
    @WebResult(name = "getLocationForGroupResponse", targetNamespace = "http://www.csapi.org/schema/location", partName = "getLocationForGroupResponse")
    public com.bsoft.client.schema.location.GetLocationForGroupResponse getLocationForGroup(
        @WebParam(partName = "getLocationForGroupRequest", name = "getLocationForGroupRequest", targetNamespace = "http://www.csapi.org/schema/location")
        com.bsoft.client.schema.location.GetLocationForGroupRequest getLocationForGroupRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/ussdContinue")
    @WebResult(name = "ussdContinueResponse", targetNamespace = "http://www.csapi.org/schema/ussd", partName = "ussdContinueResponse")
    public com.bsoft.client.schema.ussd.UssdContinueResponse ussdContinue(
        @WebParam(partName = "ussdContinueRequest", name = "ussdContinueRequest", targetNamespace = "http://www.csapi.org/schema/ussd")
        com.bsoft.client.schema.ussd.UssdContinueRequest ussdContinueRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/handleUssd")
    @WebResult(name = "handleUssdResponse", targetNamespace = "http://www.csapi.org/schema/ussd", partName = "handleUssdResponse")
    public com.bsoft.client.schema.ussd.HandleUssdResponse handleUssd(
        @WebParam(partName = "handleUssdRequest", name = "handleUssdRequest", targetNamespace = "http://www.csapi.org/schema/ussd")
        com.bsoft.client.schema.ussd.HandleUssdRequest handleUssdRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/getLocation")
    @WebResult(name = "getLocationResponse", targetNamespace = "http://www.csapi.org/schema/location", partName = "getLocationResponse")
    public com.bsoft.client.schema.location.GetLocationResponse getLocation(
        @WebParam(partName = "getLocationRequest", name = "getLocationRequest", targetNamespace = "http://www.csapi.org/schema/location")
        com.bsoft.client.schema.location.GetLocationRequest getLocationRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/startNotification")
    public void startNotification(
        @WebParam(partName = "startNotificationRequest", name = "startNotificationRequest", targetNamespace = "http://www.csapi.org/schema/notification")
        com.bsoft.client.schema.notification.StartNotificationRequest startNotificationRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/endUssd")
    public void endUssd(
        @WebParam(partName = "endUssdRequest", name = "endUssdRequest", targetNamespace = "http://www.csapi.org/schema/ussd")
        com.bsoft.client.schema.ussd.EndUssdRequest endUssdRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "APRegistration", action = "http://www.csapi.org/service/APRegistration")
    @WebResult(name = "APRegistrationRsp", targetNamespace = "http://www.csapi.org/schema/ap", partName = "APRegistrationRsp")
    public com.bsoft.client.schema.ap.APRegistrationRsp apRegistration(
        @WebParam(partName = "APRegistrationReq", name = "APRegistrationReq", targetNamespace = "http://www.csapi.org/schema/ap")
        com.bsoft.client.schema.ap.APRegistrationReq apRegistrationReq
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "PauseAP", action = "http://www.csapi.org/service/PauseAP")
    @WebResult(name = "PauseAPRsp", targetNamespace = "http://www.csapi.org/schema/ap", partName = "PauseAPRsp")
    public com.bsoft.client.schema.ap.PauseAPRsp pauseAP(
        @WebParam(partName = "PauseAPReq", name = "PauseAPReq", targetNamespace = "http://www.csapi.org/schema/ap")
        com.bsoft.client.schema.ap.PauseAPReq pauseAPReq
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "GetSmsDeliveryStatus", action = "http://www.csapi.org/service/GetSmsDeliveryStatus")
    @WebResult(name = "GetSmsDeliveryStatusResponse", targetNamespace = "http://www.csapi.org/schema/sms", partName = "GetSmsDeliveryStatusResponse")
    public com.bsoft.client.schema.sms.GetSmsDeliveryStatusResponse getSmsDeliveryStatus(
        @WebParam(partName = "GetSmsDeliveryStatusRequest", name = "GetSmsDeliveryStatusRequest", targetNamespace = "http://www.csapi.org/schema/sms")
        com.bsoft.client.schema.sms.GetSmsDeliveryStatusRequest getSmsDeliveryStatusRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/sendPush")
    @WebResult(name = "sendPushResponse", targetNamespace = "http://www.csapi.org/schema/wap", partName = "sendPushResponse")
    public com.bsoft.client.schema.wap.SendPushResponse sendPush(
        @WebParam(partName = "sendPushRequest", name = "sendPushRequest", targetNamespace = "http://www.csapi.org/schema/wap")
        com.bsoft.client.schema.wap.SendPushRequest sendPushRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/notifyMessageReception")
    public void notifyMessageReception(
        @WebParam(partName = "notifyMessageReceptionRequest", name = "notifyMessageReceptionRequest", targetNamespace = "http://www.csapi.org/schema/mms")
        com.bsoft.client.schema.mms.NotifyMessageReceptionRequest notifyMessageReceptionRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/notifyUssdEnd")
    public void notifyUssdEnd(
        @WebParam(partName = "notifyUssdEndRequest", name = "notifyUssdEndRequest", targetNamespace = "http://www.csapi.org/schema/ussd")
        com.bsoft.client.schema.ussd.NotifyUssdEndRequest notifyUssdEndRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/makeUssd")
    @WebResult(name = "makeUssdResponse", targetNamespace = "http://www.csapi.org/schema/ussd", partName = "makeUssdResponse")
    public com.bsoft.client.schema.ussd.MakeUssdResponse makeUssd(
        @WebParam(partName = "makeUssdRequest", name = "makeUssdRequest", targetNamespace = "http://www.csapi.org/schema/ussd")
        com.bsoft.client.schema.ussd.MakeUssdRequest makeUssdRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "LocationEnd", action = "http://www.csapi.org/service/LocationEnd")
    public void locationEnd(
        @WebParam(partName = "LocationEndRequest", name = "LocationEndRequest", targetNamespace = "http://www.csapi.org/schema/location")
        com.bsoft.client.schema.location.LocationEndRequest locationEndRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "APSvcAuthentic", action = "http://www.csapi.org/service/APSvcAuthentic")
    @WebResult(name = "APSvcAuthenticRsp", targetNamespace = "http://www.csapi.org/schema/ap", partName = "APSvcAuthenticRsp")
    public com.bsoft.client.schema.ap.APSvcAuthenticRsp apSvcAuthentic(
        @WebParam(partName = "APSvcAuthenticReq", name = "APSvcAuthenticReq", targetNamespace = "http://www.csapi.org/schema/ap")
        com.bsoft.client.schema.ap.APSvcAuthenticReq apSvcAuthenticReq
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/sendMessage")
    @WebResult(name = "sendMessageResponse", targetNamespace = "http://www.csapi.org/schema/mms", partName = "sendMessageResponse")
    public com.bsoft.client.schema.mms.SendMessageResponse sendMessage(
        @WebParam(partName = "sendMessageRequest", name = "sendMessageRequest", targetNamespace = "http://www.csapi.org/schema/mms")
        com.bsoft.client.schema.mms.SendMessageRequest sendMessageRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/getMessage")
    @WebResult(name = "getMessageResponse", targetNamespace = "http://www.csapi.org/schema/mms", partName = "getMessageResponse")
    public com.bsoft.client.schema.mms.GetMessageResponse getMessage(
        @WebParam(partName = "getMessageRequest", name = "getMessageRequest", targetNamespace = "http://www.csapi.org/schema/mms")
        com.bsoft.client.schema.mms.GetMessageRequest getMessageRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "RecoveryAP", action = "http://www.csapi.org/service/RecoveryAP")
    @WebResult(name = "RecoveryAPRsp", targetNamespace = "http://www.csapi.org/schema/ap", partName = "RecoveryAPRsp")
    public com.bsoft.client.schema.ap.RecoveryAPRsp recoveryAP(
        @WebParam(partName = "RecoveryAPReq", name = "RecoveryAPReq", targetNamespace = "http://www.csapi.org/schema/ap")
        com.bsoft.client.schema.ap.RecoveryAPReq recoveryAPReq
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/notifySmsReception")
    public void notifySmsReception(
        @WebParam(partName = "notifySmsReceptionRequest", name = "notifySmsReceptionRequest", targetNamespace = "http://www.csapi.org/schema/sms")
        com.bsoft.client.schema.sms.NotifySmsReceptionRequest notifySmsReceptionRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "LocationError", action = "http://www.csapi.org/service/LocationError")
    public void locationError(
        @WebParam(partName = "LocationErrorRequest", name = "LocationErrorRequest", targetNamespace = "http://www.csapi.org/schema/location")
        com.bsoft.client.schema.location.LocationErrorRequest locationErrorRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "GetReceivedSms", action = "http://www.csapi.org/service/GetReceivedSms")
    @WebResult(name = "GetReceivedSmsResponse", targetNamespace = "http://www.csapi.org/schema/sms", partName = "GetReceivedSmsResponse")
    public com.bsoft.client.schema.sms.GetReceivedSmsResponse getReceivedSms(
        @WebParam(partName = "GetReceivedSmsRequest", name = "GetReceivedSmsRequest", targetNamespace = "http://www.csapi.org/schema/sms")
        com.bsoft.client.schema.sms.GetReceivedSmsRequest getReceivedSmsRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/notifySmsDeliveryStatus")
    public void notifySmsDeliveryStatus(
        @WebParam(partName = "notifySmsDeliveryStatusRequest", name = "notifySmsDeliveryStatusRequest", targetNamespace = "http://www.csapi.org/schema/sms")
        com.bsoft.client.schema.sms.NotifySmsDeliveryStatusRequest notifySmsDeliveryStatusRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "LocationNotification", action = "http://www.csapi.org/service/LocationNotification")
    public void locationNotification(
        @WebParam(partName = "LocationNotificationRequest", name = "LocationNotificationRequest", targetNamespace = "http://www.csapi.org/schema/location")
        com.bsoft.client.schema.location.LocationNotificationRequest locationNotificationRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/getMessageDeliveryStatus")
    @WebResult(name = "getMessageDeliveryStatusResponse", targetNamespace = "http://www.csapi.org/schema/mms", partName = "getMessageDeliveryStatusResponse")
    public com.bsoft.client.schema.mms.GetMessageDeliveryStatusResponse getMessageDeliveryStatus(
        @WebParam(partName = "getMessageDeliveryStatusRequest", name = "getMessageDeliveryStatusRequest", targetNamespace = "http://www.csapi.org/schema/mms")
        com.bsoft.client.schema.mms.GetMessageDeliveryStatusRequest getMessageDeliveryStatusRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "APLogOut", action = "http://www.csapi.org/service/APLogOut")
    @WebResult(name = "APLogOutRsp", targetNamespace = "http://www.csapi.org/schema/ap", partName = "APLogOutRsp")
    public com.bsoft.client.schema.ap.APLogOutRsp apLogOut(
        @WebParam(partName = "APLogOutReq", name = "APLogOutReq", targetNamespace = "http://www.csapi.org/schema/ap")
        com.bsoft.client.schema.ap.APLogOutReq apLogOutReq
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "EndNotification", action = "http://www.csapi.org/service/EndNotification")
    public void endNotification(
        @WebParam(partName = "EndNotificationRequest", name = "EndNotificationRequest", targetNamespace = "http://www.csapi.org/schema/location")
        com.bsoft.client.schema.location.EndNotificationRequest endNotificationRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "APSvcPerfCmd", action = "http://www.csapi.org/service/APSvcPerfCmd")
    public void apSvcPerfCmd(
        @WebParam(partName = "APSvcPerfCmdReq", name = "APSvcPerfCmdReq", targetNamespace = "http://www.csapi.org/schema/ap")
        com.bsoft.client.schema.ap.APSvcPerfCmdReq apSvcPerfCmdReq
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/getReceivedMessages")
    @WebResult(name = "getReceivedMessagesResponse", targetNamespace = "http://www.csapi.org/schema/mms", partName = "getReceivedMessagesResponse")
    public com.bsoft.client.schema.mms.GetReceivedMessagesResponse getReceivedMessages(
        @WebParam(partName = "getReceivedMessagesRequest", name = "getReceivedMessagesRequest", targetNamespace = "http://www.csapi.org/schema/mms")
        com.bsoft.client.schema.mms.GetReceivedMessagesRequest getReceivedMessagesRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/notifyPushDeliveryReceipt")
    public void notifyPushDeliveryReceipt(
        @WebParam(partName = "notifyPushDeliveryReceiptRequest", name = "notifyPushDeliveryReceiptRequest", targetNamespace = "http://www.csapi.org/schema/wap")
        com.bsoft.client.schema.wap.NotifyPushDeliveryReceiptRequest notifyPushDeliveryReceiptRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "APSvcAlarm", action = "http://www.csapi.org/service/APSvcAlarm")
    @WebResult(name = "AlarmRsp", targetNamespace = "http://www.csapi.org/schema/ap", partName = "AlarmRsp")
    public com.bsoft.client.schema.ap.AlarmRsp apSvcAlarm(
        @WebParam(partName = "AlarmReq", name = "AlarmReq", targetNamespace = "http://www.csapi.org/schema/ap")
        com.bsoft.client.schema.ap.AlarmReq alarmReq
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/stopNotification")
    public void stopNotification(
        @WebParam(partName = "stopNotificationRequest", name = "stopNotificationRequest", targetNamespace = "http://www.csapi.org/schema/notification")
        com.bsoft.client.schema.notification.StopNotificationRequest stopNotificationRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/notifyMessageDeliveryReceipt")
    public void notifyMessageDeliveryReceipt(
        @WebParam(partName = "notifyMessageDeliveryReceiptRequest", name = "notifyMessageDeliveryReceiptRequest", targetNamespace = "http://www.csapi.org/schema/mms")
        com.bsoft.client.schema.mms.NotifyMessageDeliveryReceiptRequest notifyMessageDeliveryReceiptRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(operationName = "APSvcPerfReport", action = "http://www.csapi.org/service/APSvcPerfReport")
    public void apSvcPerfReport(
        @WebParam(partName = "APSvcPerfReportReq", name = "APSvcPerfReportReq", targetNamespace = "http://www.csapi.org/schema/ap")
        com.bsoft.client.schema.ap.APSvcPerfReportReq apSvcPerfReportReq
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/startPeriodicNotification")
    @WebResult(name = "startPeriodicNotificationResponse", targetNamespace = "http://www.csapi.org/schema/location", partName = "startPeriodicNotificationResponse")
    public com.bsoft.client.schema.location.StartPeriodicNotificationResponse startPeriodicNotification(
        @WebParam(partName = "startPeriodicNotificationRequest", name = "startPeriodicNotificationRequest", targetNamespace = "http://www.csapi.org/schema/location")
        com.bsoft.client.schema.location.StartPeriodicNotificationRequest startPeriodicNotificationRequest
    ) throws ServiceException, PolicyException;

    @WebMethod(action = "http://www.csapi.org/service/sendSms")
    @WebResult(name = "sendSmsResponse", targetNamespace = "http://www.csapi.org/schema/sms", partName = "sendSmsResponse")
    public com.bsoft.client.schema.sms.SendSmsResponse sendSms(
        @WebParam(partName = "sendSmsRequest", name = "sendSmsRequest", targetNamespace = "http://www.csapi.org/schema/sms")
        com.bsoft.client.schema.sms.SendSmsRequest sendSmsRequest
    ) throws ServiceException, PolicyException;
}
