
package com.bsoft.client.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-10-25T10:56:06.187+08:00
 * Generated source version: 3.0.15
 */

@WebFault(name = "PolicyException", targetNamespace = "http://www.csapi.org/schema/common/v2_0")
public class PolicyException extends Exception {
    
    private com.bsoft.client.schema.common.v2_0.PolicyException policyException;

    public PolicyException() {
        super();
    }
    
    public PolicyException(String message) {
        super(message);
    }
    
    public PolicyException(String message, Throwable cause) {
        super(message, cause);
    }

    public PolicyException(String message, com.bsoft.client.schema.common.v2_0.PolicyException policyException) {
        super(message);
        this.policyException = policyException;
    }

    public PolicyException(String message, com.bsoft.client.schema.common.v2_0.PolicyException policyException, Throwable cause) {
        super(message, cause);
        this.policyException = policyException;
    }

    public com.bsoft.client.schema.common.v2_0.PolicyException getFaultInfo() {
        return this.policyException;
    }
}
