
package com.bsoft.client.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-10-25T10:56:06.151+08:00
 * Generated source version: 3.0.15
 */

@WebFault(name = "ServiceException", targetNamespace = "http://www.csapi.org/schema/common/v2_0")
public class ServiceException extends Exception {
    
    private com.bsoft.client.schema.common.v2_0.ServiceException serviceException;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, com.bsoft.client.schema.common.v2_0.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException(String message, com.bsoft.client.schema.common.v2_0.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public com.bsoft.client.schema.common.v2_0.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
