
package com.bsoft.client.mscf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HISWebServiceSoap", targetNamespace = "http://tempuri.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HISWebServiceSoap {


    /**
     * 
     * @param inputParameter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/DHC.HIS.BS.HISWebService.HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org", className = "com.bsoft.webs.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org", className = "com.bsoft.webs.HelloWorldResponse")
    public String helloWorld(
        @WebParam(name = "InputParameter", targetNamespace = "http://tempuri.org")
        String inputParameter);

    /**
     * 
     * @param inputParameter
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HisWebService", action = "http://tempuri.org/DHC.HIS.BS.HISWebService.HisWebService")
    @WebResult(name = "HisWebServiceResult", targetNamespace = "http://tempuri.org")
    @RequestWrapper(localName = "HisWebService", targetNamespace = "http://tempuri.org", className = "com.bsoft.webs.HisWebService")
    @ResponseWrapper(localName = "HisWebServiceResponse", targetNamespace = "http://tempuri.org", className = "com.bsoft.webs.HisWebServiceResponse")
    public String hisWebService(
        @WebParam(name = "InputParameter", targetNamespace = "http://tempuri.org")
        String inputParameter);

}
